Document: fsearch-trunk
Title: Debian fsearch-trunk Manual
Author: <insert document author here>
Abstract: This manual describes what fsearch-trunk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fsearch-trunk/fsearch-trunk.sgml.gz

Format: postscript
Files: /usr/share/doc/fsearch-trunk/fsearch-trunk.ps.gz

Format: text
Files: /usr/share/doc/fsearch-trunk/fsearch-trunk.text.gz

Format: HTML
Index: /usr/share/doc/fsearch-trunk/html/index.html
Files: /usr/share/doc/fsearch-trunk/html/*.html
