.TH FSEARCH "1" "2021-07-17"
.
.SH NAME
FSearch \- a graphical file search utility
.
.SH SYNOPSIS
.B fsearch
.RI [ OPTIONS ]
.
.SH DESCRIPTION
.B FSearch
allows you to search for files and folders by name. It uses an index to provide results almost instantly as you type.
.
.SH OPTIONS
.SS "Help Options"
.TP
.BR \-h ", " \-\^\-help
Show help options
.TP
.BR \-\^\-help\-all
Show all help options
.SS "Application Options"
.TP
.BR \-\^\-minimized
Minimize the application window
.TP
.BR \-\^\-new-window
Open a new application window
.TP
.BR \-\^\-preferences
Show the application preferences
.TP
.BI \-s " PATTERN" "\fR,\fP \-\^\-search=" PATTERN
Set the search pattern
.TP
.BR \-u ", " \-\^\-update-database
Update the database
.TP
.BR \-v ", " \-\^\-version
Print version information and exit
.TP
.BI "\-\^\-display=" DISPLAY
X display to use
.
.SH BUGS
For any bugs or feature requests, please create an issue on GitHub at https://github.com/cboxdoerfer/fsearch/issues
.
.SH AUTHORS
Christian Boxdörfer and contributors
