#pragma once

typedef enum FsearchDatabaseEntryFlags {
    FSEARCH_DATABASE_ENTRY_FLAG_TYPE_FOLDER = 1 << 0,
    FSEARCH_DATABASE_ENTRY_FLAG_TYPE_FILE = 1 << 1,
    FSEARCH_DATABASE_ENTRY_FLAG_MARKED = 1 << 2,
    FSEARCH_DATABASE_ENTRY_FLAG_MONITORED_INOTIFY = 1 << 3,
    FSEARCH_DATABASE_ENTRY_FLAG_MONITORED_FANOTIFY = 1 << 4,
    FSEARCH_DATABASE_ENTRY_FLAG_DELETED = 1 << 15,
} FsearchDatabaseEntryFlags;
