#pragma once

typedef enum {
    FSEARCH_SELECTION_TYPE_CLEAR,
    FSEARCH_SELECTION_TYPE_ALL,
    FSEARCH_SELECTION_TYPE_INVERT,
    FSEARCH_SELECTION_TYPE_SELECT,
    FSEARCH_SELECTION_TYPE_TOGGLE,
    FSEARCH_SELECTION_TYPE_SELECT_RANGE,
    FSEARCH_SELECTION_TYPE_TOGGLE_RANGE,
    NUM_FSEARCH_SELECTION_TYPES,
} FsearchSelectionType;
